Repository openmsupply/conforma-web-app, pull requests merged in 2021-09, with the labels that each got.

#1000 #587B - part2 Use package pluralization to set lookupTable always in plural form
  package.json
  src/LookupTable/components/ImportCsvModal.tsx
  src/LookupTable/types.ts
  src/utils/generated/graphql.tsx
Labels: #toDemo

#983 #976 Outcomes display using API
  semantic/src/site/collections/table.overrides
  semantic/src/site/globals/site.overrides
  src/components/List/Pagination.tsx
  src/containers/Main/SiteLayout.tsx
  src/containers/Outcomes/ApplicationLinks.tsx
  src/containers/Outcomes/Outcomes.tsx
  src/containers/Outcomes/OutcomesDetail.tsx
  src/containers/Outcomes/OutcomesDetailWrapper.tsx
  src/containers/Outcomes/OutcomesList.tsx
  src/containers/Outcomes/OutcomesTable.tsx
  src/containers/Outcomes/OutcomesTableWrapper.tsx
  src/containers/Outcomes/contexts/helpers.ts
  src/containers/Outcomes/contexts/outcomesState.tsx
  src/containers/Outcomes/helpers.tsx
  src/containers/User/UserArea.tsx
  src/formElementPlugins/listBuilder/src/styles.less
  src/utils/constants.ts
  src/utils/data/LuxonDateTimeConstants.ts
  src/utils/data/globalConstants.ts
  src/utils/generated/graphql.tsx
  src/utils/graphql/queries/getOutcomeDisplays.query.ts
  src/utils/helpers/semanticReactMarkdown.tsx
  src/utils/helpers/utilityFunctions.ts
  src/utils/hooks/useOutcomes.tsx
  src/utils/hooks/usePageTitle.ts
  src/utils/hooks/useQuerySectionActivation.tsx
  src/utils/types.ts
Labels: #inDemo

#990 #879 Show different title when application is completed
  src/containers/Application/ApplicationSummary.tsx
  src/utils/constants.ts
  src/utils/generated/graphql.tsx
Labels: #inDemo

#997 #587B Quick fix to allow viewing lookup tables inserted with plural names
  package.json
  src/LookupTable/components/ImportCsvModal.tsx
  src/LookupTable/contexts/LookUpTableImportCsvContext.tsx
  src/LookupTable/graphql/getDynamicSingleTable.query.ts
  src/LookupTable/hooks/useGetSingleTable.hook.tsx
  src/LookupTable/types.ts
Labels: #inDemo

#974 #285 delete application in draft
  semantic/src/site/globals/site.overrides
  src/components/List/ApplicationsList.tsx
  src/components/List/Cells/ApplicationNameCells.tsx
  src/components/List/Cells/StatusCell.tsx
  src/containers/List/ListWrapper.tsx
  src/utils/constants.ts
  src/utils/generated/graphql.tsx
  src/utils/graphql/mutations/deleteApplication.mutation.ts
  src/utils/hooks/useListApplications.tsx
  src/utils/messages.ts
  src/utils/types.ts
Labels: #inDemo

#989 #964 Number plugin fix (2)
  src/formElementPlugins/number/src/ApplicationView.tsx
Labels: #inDemo

#1014 Core_templates snapshot v1
  docs/internal/Home.md
  docs/internal/admin/List-Core-Actions.md
  docs/internal/admin/Template-Builder.md
Labels: PR: Needs to update wiki
