Repository openmsupply/conforma-web-app, pull requests merged in 2021-11, with the labels that each got.

#1030 Quick fix: File upload summary view
  src/formElementPlugins/fileUpload/src/SummaryView.tsx
Labels: #toDemo

#1031 #1029 add field is interactive to template
  docs/internal/admin/Template-Builder.md
  src/containers/Review/ReviewSubmit.tsx
  src/containers/TemplateBuilder/template/General/General.tsx
  src/containers/TemplateBuilder/template/TemplateWrapper.tsx
  src/utils/generated/graphql.tsx
  src/utils/graphql/fragments/template.fragment.ts
  src/utils/hooks/useGetDecisionOptions.ts
  src/utils/hooks/useLoadApplication.ts
  src/utils/types.ts
Labels: PR: Needs to update wiki, #toDemo

#1050 #620B Note about proper Markdown links in email notifications
  docs/internal/admin/Template-Builder.md
Labels: Docs: Internal, Epic #85: Bug Fixes (and refactor), Sprint29
