Repository openmsupply/conforma-web-app, pull requests merged in 2022-11, with the labels that each got.

#1386 #1384 Access documents in question history panel
  src/components/PageElements/Elements/HistoryResponseElement.tsx
  src/components/Review/HistoryPanel.tsx
  src/utils/hooks/useGetQuestionReviewHistory.tsx
  src/utils/types.ts
Labels: Dev

#1421 #1408 improving assignment
  package.json
  src/components/Review/ReviewSectionRowAction.tsx
  src/containers/Review/assignment/AssignAll.tsx
  src/containers/Review/assignment/AssigneeDropdown.tsx
  src/containers/Review/assignment/AssignmentRows.tsx
  src/containers/Review/assignment/AssignmentSectionRow.tsx
  src/containers/Review/assignment/AssignmentSubmit.tsx
  src/containers/Review/assignment/AssignmentTab.tsx
  src/containers/Review/assignment/Reassignment.tsx
  src/containers/Review/assignment/ReviewLevel.tsx
  src/containers/Review/assignment/ReviewSectionRow.tsx
  src/containers/Review/assignment/useGetAssignmentOptions.ts
  src/utils/generated/graphql.tsx
  src/utils/hooks/useCreateFinalDecisionReview.ts
  src/utils/hooks/useGetReviewInfo.tsx
  src/utils/hooks/useLoadAssignments.tsx
  src/utils/hooks/useTriggers.tsx
  src/utils/hooks/useUpdateAssignment.tsx
  src/utils/types.ts
Labels: Feature: improvement, Dev

#1425 #1420 Hide reassign from list actions
  src/components/List/ApplicationsList.tsx
  src/components/List/Cells/ReviewerActionCell.tsx
  src/containers/List/ListWrapper.tsx
Labels: Customer: Angola, Customer: Fiji

#1435 #1431 Reassignment fix
  src/utils/generated/graphql.tsx
  src/utils/hooks/useUpdateAssignment.tsx
Labels: Bug: development

#1430 #1429 Template builder fallbacks fixes
  src/containers/TemplateBuilder/evaluatorGui/EvaluationFallback.tsx
  src/containers/TemplateBuilder/evaluatorGui/guiDefinitions.tsx
Labels: Bug: development, Bug: production, Bugs during tests, Customer: Angola, Customer: Fiji

#1441 #1440 Search plugin - "input" mode
  docs/internal/Element-Type-Specs.md
  src/formElementPlugins/search/src/ApplicationView.tsx
Labels: Feature: improvement

#1448 #1445 move checks for admin manager inside current user
  src/components/Admin/Admin.tsx
  src/components/Main/Footer.tsx
  src/config.ts
  src/containers/Dev/UserSelection.tsx
  src/containers/User/Login.tsx
  src/containers/User/NonRegisteredLogin.tsx
  src/containers/User/UserArea.tsx
  src/contexts/UserState.tsx
  src/utils/helpers/fetchUserInfo.ts
  src/utils/hooks/useReferenceDocs.ts
  src/utils/types.ts
Labels: importance: Should have, Dev

#1452 #1451 List pagination fix
  src/utils/helpers/list/buildQueryVariables.ts
  src/utils/hooks/useListApplications.tsx
Labels: Bug: development, Bug: production, Customer: Angola, Customer: Fiji
