Repository openmsupply/conforma-web-app, pull requests merged in 2022-02, with the labels that each got.

#1086 #1085 Review Page tab structure
  semantic/src/site/globals/site.overrides
  src/components/List/Cells/ReviewerActionCell.tsx
  src/containers/Review/ProgressBar.tsx
  src/containers/Review/ReviewPageWrapper.tsx
  src/containers/Review/ReviewWrapper.tsx
  src/containers/Review/assignment/AssigneeDropdown.tsx
  src/containers/Review/assignment/Assignment.tsx
  src/containers/Review/assignment/AssignmentSectionRow.tsx
  src/containers/Review/assignment/AssignmentTab.tsx
  src/containers/Review/assignment/Reassignment.tsx
  src/containers/Review/assignment/ReviewSectionRow.tsx
  src/containers/Review/assignment/useGetAssignmentOptions.ts
  src/containers/Review/documents/DocumentsTab.tsx
  src/containers/Review/index.ts
  src/containers/Review/notes/NotesTab.tsx
  src/containers/Review/overview/OverviewTab.tsx
  src/containers/Review/summary/SummaryTab.tsx
  src/utils/defaultLanguageStrings.ts
  src/utils/generated/graphql.tsx
Labels: Feature: improvement

#1092 #1084 Progress bar
  .gitignore
  package.json
  semantic/src/site/globals/site.overrides
  src/containers/Review/ProgressBar.tsx
  src/utils/defaultLanguageStrings.ts
  yarn-error.log
  yarn.lock
Labels: Feature: new

#1093 #1083 Overview tab / timeline
  semantic/src/site/globals/site.overrides
  semantic/src/site/globals/site.variables
  src/components/List/Cells/ReviewerActionCell.tsx
  src/components/Review/ReviewContainer.tsx
  src/containers/Review/ReviewWrapper.tsx
  src/containers/Review/overview/Overview.tsx
  src/containers/Review/overview/OverviewTab.tsx
  src/containers/Review/overview/TimelineStage.tsx
  src/utils/defaultLanguageStrings.ts
  src/utils/hooks/useTimeline/eventInterpretation.ts
  src/utils/hooks/useTimeline/types.ts
  src/utils/hooks/useTimeline/useTimeline.tsx
Labels: Feature: new

#1096 #1082 Documents tab
  semantic/src/site/globals/site.overrides
  src/containers/Review/documents/DocumentsTab.tsx
  src/utils/defaultLanguageStrings.ts
  src/utils/generated/graphql.tsx
  src/utils/graphql/queries/getDocuments.query.ts
Labels: Feature: new

#1097 #1087 assignment with submit button
  semantic/src/site/elements/label.overrides
  src/components/Review/ReviewSectionRowAction.tsx
  src/components/Review/ReviewSectionRowAssigned.tsx
  src/containers/Review/assignment/AssigneeDropdown.tsx
  src/containers/Review/assignment/AssigneeLabel.tsx
  src/containers/Review/assignment/Assignment.tsx
  src/containers/Review/assignment/AssignmentSectionRow.tsx
  src/containers/Review/assignment/Reassignment.tsx
  src/containers/Review/assignment/ReviewSectionRow.tsx
  src/containers/Review/assignment/useGetAssignmentOptions.ts
  src/utils/data/assignmentOptions.ts
  src/utils/defaultLanguageStrings.ts
  src/utils/hooks/useReassignReviewAssignment.ts
  src/utils/hooks/useUpdateReviewAssignment.tsx
  src/utils/types.ts
Labels: Bug: development

#1102 #1079 Notes tab
  package.json
  semantic/src/site/globals/site.overrides
  src/components/PageElements/Elements/ApplicantResponseElement.tsx
  src/components/PageElements/Elements/ReviewInlineInput.tsx
  src/components/PageElements/Elements/ReviewResponseElement.tsx
  src/containers/Review/ReviewWrapper.tsx
  src/containers/Review/notes/NewCommentForm.tsx
  src/containers/Review/notes/NotesTab.tsx
  src/containers/Review/overview/OverviewTab.tsx
  src/containers/Review/overview/TimelineStage.tsx
  src/containers/TemplateBuilder/template/Actions/ActionConfig.tsx
  src/containers/TemplateBuilder/template/Form/ElementConfig.tsx
  src/containers/TemplateBuilder/template/General/Categories.tsx
  src/utils/defaultLanguageStrings.ts
  src/utils/generated/graphql.tsx
  src/utils/graphql/mutations/createNote.mutation.ts
  src/utils/graphql/mutations/deleteNote.mutation.ts
  src/utils/graphql/queries/getNotes.query.ts
  src/utils/hooks/useNotesMutations.tsx
  yarn.lock
Labels: Feature: new

#1116 #1115 refactor assignments full structure with review structures state
  src/components/Review/ReviewSectionRowAction.tsx
  src/components/Review/ReviewSectionRowAssigned.tsx
  src/components/Review/ReviewSectionRowLastActionDate.tsx
  src/containers/Review/ReviewPage.tsx
  src/containers/Review/ReviewSubmit.tsx
  src/containers/Review/ReviewWrapper.tsx
  src/containers/Review/assignment/Assignment.tsx
  src/containers/Review/assignment/AssignmentRows.tsx
  src/containers/Review/assignment/AssignmentSectionRow.tsx
  src/containers/Review/assignment/AssignmentSubmit.tsx
  src/containers/Review/assignment/AssignmentTab.tsx
  src/containers/Review/assignment/Reassignment.tsx
  src/containers/Review/assignment/ReviewSectionRow.tsx
  src/containers/Review/assignment/useGetAssignmentOptions.ts
  src/contexts/ReviewStructuresState.tsx
  src/utils/generated/graphql.tsx
  src/utils/graphql/fragments/reviewAssignment.fragment.ts
  src/utils/helpers/structure/generateConsolidatorResponsesProgress.ts
  src/utils/helpers/structure/generateFinalDecisionProgress.ts
  src/utils/helpers/structure/generateReviewSectionActions.ts
  src/utils/helpers/structure/generateReviewerResponsesProgress.ts
  src/utils/hooks/useCreateReview.tsx
  src/utils/hooks/useGetDecisionOptions.ts
  src/utils/hooks/useGetReviewInfo.tsx
  src/utils/hooks/useGetReviewStructureForSection/helpers.tsx
  src/utils/hooks/useGetReviewStructureForSection/useGetReviewStructureForSection.tsx
  src/utils/hooks/useRemakePreviousReview.ts
  src/utils/hooks/useRestartReview.ts
  src/utils/hooks/useUpdateReviewAssignment.tsx
  src/utils/types.ts
Labels: Feature: refactor

#1118 #1074 List text adjustment
  src/components/List/Cells/LastActiveDateCell.tsx
Labels: Bug: development

#1121 1110 fix bugs related to assignment consolidation
  src/components/Review/ReviewSectionRowAction.tsx
  src/containers/Review/ReviewPage.tsx
  src/containers/Review/assignment/AssigneeLabel.tsx
  src/containers/Review/assignment/AssignmentRows.tsx
  src/containers/Review/assignment/AssignmentSectionRow.tsx
  src/containers/Review/assignment/ReviewSectionRow.tsx
  src/containers/Review/assignment/useGetAssignmentOptions.ts
  src/utils/helpers/structure/generateConsolidatorResponsesProgress.ts
  src/utils/hooks/useCreateReview.tsx
  src/utils/hooks/useRemakePreviousReview.ts
  src/utils/hooks/useRestartReview.ts
  src/utils/types.ts
Labels: Bug: development

#1119 #1032 Restore text element default
  docs/internal/Element-Type-Specs.md
  src/formElementPlugins/longText/pluginConfig.json
  src/formElementPlugins/longText/src/ApplicationView.tsx
  src/formElementPlugins/shortText/src/ApplicationView.tsx
Labels: Feature: improvement
