Repository openmsupply/conforma-web-app, pull requests merged in 2022-08, with the labels that each got.

#1228 #1177 Help reference docs
  semantic/src/site/globals/site.overrides
  src/containers/User/UserArea.tsx
  src/utils/defaultLanguageStrings.ts
  src/utils/generated/graphql.tsx
  src/utils/graphql/queries/getReferenceDocs.query.ts
  src/utils/hooks/useReferenceDocs.ts
Labels: Feature: new, Epic effort: 5, Dev, Requested: Armed, Phase 2, Approved: MVP

#1306 #1298 Checkbox improvements
  docs/internal/Element-Type-Specs.md
  semantic/src/site/globals/site.variables
  src/formElementPlugins/checkbox/src/ApplicationView.tsx
  src/formElementPlugins/checkbox/src/SummaryView.tsx
  src/formElementPlugins/fileUpload/src/SummaryView.tsx
  src/utils/types.ts
Labels: Feature: improvement, Phase 2, Approved: MVP

#1307 1300 Don't display time with deadline
  src/components/List/Cells/DeadlineCell.tsx
  src/containers/Review/overview/Overview.tsx
Labels: Dev, Approved: MVP

#1315 #1291 Fix "Manage" menu bar item
  src/config.ts
  src/contexts/UserState.tsx
  src/utils/helpers/fetchUserInfo.ts
Labels: Bug: development, Phase 2

#1317 #1316 Number input improvements
  docs/internal/Element-Type-Specs.md
  src/formElementPlugins/number/src/ApplicationView.tsx
Labels: Feature: improvement, Phase 2

#1309 #1303 - Part 2 - Fix assignment available for applications Reviewed or Assigned by others
  src/containers/Review/assignment/AssignmentSubmit.tsx
  src/utils/generated/graphql.tsx
  src/utils/hooks/useUpdateAssignment.tsx
Labels: Bug: development, Dev, Approved: MVP

#1314 #1199 Optionally reviewable elements
  src/components/PageElements/Elements/ReviewApplicantResponse.tsx
  src/components/PageElements/Elements/ReviewInlineInput.tsx
  src/components/PageElements/Elements/ReviewInlineNewResponse.tsx
  src/components/PageElements/PageElements.tsx
  src/components/Review/ReviewDecision.tsx
  src/components/Sections/SectionWrapper.tsx
  src/containers/Review/ReviewPage.tsx
  src/containers/TemplateBuilder/template/Form/ElementConfig.tsx
  src/utils/generated/graphql.tsx
  src/utils/graphql/mutations/createReviewResponse.mutation.ts
  src/utils/hooks/useGetReviewStructureForSection/helpers.tsx
  src/utils/types.ts
Labels: Feature: new, Epic effort: 5, Dev, Requested: Armed, Phase 2, Approved: MVP

#1319 #1299 Assign reviewer to all levels at once
  semantic/src/site/globals/site.overrides
  src/components/Tooltip.tsx
  src/containers/Review/assignment/AssignAll.tsx
  src/containers/Review/assignment/AssignmentRows.tsx
  src/containers/Review/assignment/AssignmentTab.tsx
  src/utils/defaultLanguageStrings.ts
Labels: Dev, Approved: MVP

#1320 Add correct config info to applicationData
  src/containers/DataDisplay/helpers.tsx
  src/formElementPlugins/fileUpload/src/SummaryView.tsx
Labels: Bug: development, Phase 2, Approved: MVP

#1323 Quick fix: Display checkbox summary even when no response
  src/formElementPlugins/checkbox/src/SummaryView.tsx
Labels: Bug: development, Phase 2, Approved: MVP

#1326 #1324 Assign all fix
  src/containers/Review/assignment/AssignAll.tsx
  src/containers/Review/assignment/AssignmentTab.tsx
Labels: Bug: development, Phase 2, Approved: MVP
