Repository openmsupply/conforma-web-app, pull requests merged in 2022-09, with the labels that each got.

#1328 #946 Don't show invalid review responses in history panel
  src/utils/hooks/useGetQuestionReviewHistory.tsx
Labels: Bug: development, Phase 2, Bugs during tests

#1337 #1302 Intermittent problem submitting Product Registration
  src/utils/hooks/useSubmitApplication.tsx
Labels: Bug: development, Approved: MVP, Bugs during tests

#1348 #1346 Update substituteValues in plugins
  src/formElementPlugins/listBuilder/src/displayComponents/ListCardLayout.tsx
  src/formElementPlugins/listBuilder/src/displayComponents/ListInlineLayout.tsx
  src/formElementPlugins/listBuilder/src/displayComponents/ListListLayout.tsx
  src/formElementPlugins/listBuilder/src/helpers.ts
  src/formElementPlugins/search/src/ApplicationView.tsx
Labels: Feature: improvement

#1350 #825F Data View front-end changes
  src/containers/DataDisplay/DataViewDetail.tsx
  src/containers/DataDisplay/DataViewTable.tsx
  src/containers/DataDisplay/DataViews.tsx
  src/containers/User/UserArea.tsx
  src/utils/helpers/endpoints/endpointUrlBuilder.ts
  src/utils/helpers/endpoints/types.ts
  src/utils/hooks/useDataViews.tsx
  src/utils/types.ts
Labels: Bug: development, Epic #85: Bug Fixes (and refactor), Sprint43

#1354 #1353 Fix search box
  src/config.ts
  src/containers/List/ListWrapper.tsx
  src/formElementPlugins/search/localisation/pt_an/strings.json
  src/formElementPlugins/search/src/useDebounce.ts
Labels: Bug: development

#1353 #1351 - Hide option to edit/add reviews on elements in re-assigned sections
  src/components/PageElements/Elements/ReviewApplicantResponse.tsx
  src/containers/Review/ReviewPage.tsx
Labels: Bug: development, Phase 2, Bugs during tests
