Repository openmsupply/conforma-web-app, pull requests merged in 2022-10, with the labels that each got.

#1362 #1361 Application list -- default filters fix
  src/containers/List/ListFilters/ListFilters.tsx
  src/utils/helpers/list/useGetFilterDefinitions.ts
Labels: Bug: development, Approved: MVP

#1371 #1370 - Fix applications list for ReviewAll permissions users
  src/utils/helpers/list/findUserRole.ts
Labels: Bug: production

#1374 #1232 Fix Applicant summary page re-direct loop
  src/containers/Application/ApplicationSummary.tsx
  src/utils/hooks/useGetApplicationStructure.tsx
Labels: Bug: production, Phase 2

#1360 866F Data view filtering
  semantic/src/site/globals/site.overrides
  src/components/List/Pagination.tsx
  src/containers/DataDisplay/DataViewDetail.tsx
  src/containers/DataDisplay/DataViewFilters.tsx
  src/containers/DataDisplay/DataViewTable.tsx
  src/containers/DataDisplay/helpers.tsx
  src/containers/List/ListFilters/ListFilters.tsx
  src/containers/List/ListFilters/OptionFilters.tsx
  src/containers/User/UserArea.tsx
  src/contexts/SystemPrefs.tsx
  src/formElementPlugins/search/src/ApplicationView.tsx
  src/utils/defaultLanguageStrings.ts
  src/utils/helpers/list/buildQueryFilters.ts
  src/utils/helpers/utilityFunctions.ts
  src/utils/hooks/useDataViews.tsx
  src/utils/types.ts
Labels: Bug: development, Bugs during tests

#1396 #1378 & #891B Improve apply button performance
  src/containers/Review/assignment/Assignment.tsx
  src/containers/Review/assignment/AssignmentRows.tsx
  src/containers/Review/assignment/AssignmentSubmit.tsx
  src/containers/Review/assignment/AssignmentTab.tsx
  src/containers/Review/assignment/ReviewSectionRow.tsx
  src/contexts/ReviewStructuresState.tsx
  src/utils/hooks/useGetReviewInfo.tsx
  src/utils/hooks/useUpdateAssignment.tsx
Labels: importance: Should have, Dev

#1391 #32T check fully reviewed before approved based
  package.json
  src/containers/Review/ReviewSubmit.tsx
  src/containers/Review/assignment/AssignmentTab.tsx
  src/containers/TemplateBuilder/template/Form/ElementConfig.tsx
  src/utils/defaultLanguageStrings.ts
  src/utils/generated/graphql.tsx
  src/utils/graphql/queries/getReviewableQuestions.query.ts
  src/utils/hooks/useSubmitReview.ts
  src/utils/hooks/useTimeline/eventInterpretation.ts
Labels: Bug: development, Phase 2, Bugs during tests

#1410 Fix incorrect decision on review submit
  src/containers/Review/ReviewSubmit.tsx
Labels: Urgent
